kiwi/config/routes.rb
Rails.application.routes.draw do

 resources :questions do
  resources :comments, only: [:new, :create, :update]
  resources :answers, only: [:create]
  resources :votes, only: [ :create, :destroy ]
 end

 resources :answers do
  resources :comments, only: [:new, :create, :update]
  resources :votes, only: [:create, :destroy]
  patch 'best', on: :member
 end

 resources :comments, only: [ :edit, :destroy ]

  resources :users, only: [ :new, :show, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]

  root 'questions#index'

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

end

kiwi/app/models/question.rb
class Question < ActiveRecord::Base
  include Votable

  belongs_to :user
  has_many :answers
  has_many :answer_votes, through: :answers, source: :votes
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  #validate object in preference to id
  validates_presence_of :title, :content, :user

  def comments_by_recency
    comments.order(created_at: :desc)
  end

  def best_answer
    #move the knowledge of the internals of Answer into Answer
    Answer.best_for_question(self)
  end

  def sort_answers_by_votes
    # We can do this (honestly....) in AR
    answers.joins(:votes).group(:id).order('sum(votes.direction)')
  end

end

kiwi/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    if params[:sort] == "trend"

    elsif params[:sort] == "recent"
      @questions = Question.all.order(:created_at)
    elsif params[:sort] == "rate"
      # TODO: add a scope on question for this
      @questions = Question.all.sort_by { |question| question.sum_of_votes }.reverse
    else
      @questions = Question.all
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(id: @question.id)
    else
      render :new
    end
  end

  def show
    @question = Question.includes(:answers, :user).find(params[:id])
    @question.increment(:views).save
    @answers = @question.sort_answers_by_votes
    @answer = Answer.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    @question = Question.find_by(id: params[:id])
    if @question.update_attributes(question_params)
      redirect_to question_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title,:content,:user_id,:best_answer_id)
  end
end

kiwi/app/helpers/questions_helper.rb
module QuestionsHelper
end

kiwi/app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <fieldset id="form">
    <div class="input-options">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="input-options">
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>

    <%= f.submit 'Save your question' %>
  </fieldset>
<% end %>

kiwi/app/views/questions/edit.html.erb
<h2>Edit Your Question</h2>

<%= render partial: "form" %>

kiwi/app/views/questions/index.html.erb
<h2>All Questions</h2>

<div class="sort-by-menu">
  <ul class="sort-by-nav">
    <p class="sort-by-options"> Sort By </p>
    <li class="sort-by-options"><%= link_to "Trending", root_path(sort: "trending") %></li> |
    <li class="sort-by-options"><%= link_to "Most Recent", root_path(sort: "most-recent") %></li> |
    <li class="sort-by-options"><%= link_to "Highest-Voted", root_path(sort: "rate")%></li>
  </ul>
</div>

<% if @questions %>
  <% @questions.each do |question| %>
    <div class="question-container">
      <div class="question-stats">
        <div class="votes"><%= question.sum_of_votes %></div>
        <div class="votes-label">votes</div>

        <div class="answers"><%= question.answers.count %></div>
        <div class="answers-label">answers</div>

        <div class="views"><%= question.views %></div>
        <div class="views-label">views</div>
      </div>
      <div class="question-links">
        <%= link_to question.title, question_path(question) %>
      </div>
    </div>
  <% end %>
<% end %>

kiwi/app/views/questions/new.html.erb
<h2>Post a new question</h2>

<%= render partial: "form" %>

kiwi/app/views/questions/show.html.erb
<div class="question">
  <h3 id="question-title"><%= @question.title %></h3>

  <div class="vote-container">
    <ul class="vote-attributes">
      <li id="up-vote"><%= link_to '&#x25B2'.html_safe, question_votes_path(@question, vote: {direction: '1'}), method: :post %></li>
      <li><%= @question.sum_of_votes %></li>
      <li id="down-vote"><%= link_to '&#x25BC'.html_safe, question_votes_path(@question, vote: {direction: '-1'}), method: :post %></li>
    </ul>
  </div>

  <span class="user-time">Asked by <%= @question.user.name %> <%= std_format_date(@question.created_at) %></span>

  <p id="question-content"><%= @question.content %></p>

  <ul>
    <% if current_user == @question.user %>
      <li><%= link_to "Edit my question", edit_question_path %></li>
      <li><%= link_to "Delete my question", question_path, method: :delete %></li>
    <% end %>
  </ul>

  <% if !@question.comments.empty? %>
    <div class="comments">
      <h5>Comments:</h5>
      <% @question.comments_by_recency.each do |comment| %>
        <p class="comment"><%= comment.content %> &bull; <span class="user-time"><%= comment.user.name %> <%= std_format_date(comment.created_at) %></span>  <% if comment.owned_by?(current_user) %> &bull; <%= link_to "Edit", edit_comment_path(comment.id) %> &bull; <%= link_to "Delete",comment_path(comment.id), method: :delete, data: {confirm: 'Are you sure?'}  %><% end %></p>
      <% end %>
    </div>
  <% end %>
</div>

<% if logged_in? %>
  <ul>
    <li><%= link_to "Add Comment", new_question_comment_path(@question.id) %></li>
  </ul>
<% end %>


<% if @answers.any? %>
  <div class="answers-list">
    <h4>Answers: <%= @answers.count %></h4>
    <% if @question.best_answer_id %>
      <%= render partial: "answers/answer_show", layout: false, locals: { answer: @question.best_answer} %>
    <% end %>
    <% @answers.each do |answer|%>
      <% if answer.id != @question.best_answer_id %>
        <%= render partial: "answers/answer_show", layout: false, locals: { answer: answer} %>
      <% end %>
    <% end %>
  </div>
<% end %>

<hr>

<h4>Add Your Answer:</h4>
<div id="answers-form">
  <%= render "answers/form" %>
</div>