kiwi/config/routes.rb
Rails.application.routes.draw do

 resources :questions do
  resources :comments, only: [:new, :create, :update]
  resources :answers, only: [:create]
  resources :votes, only: [ :create, :destroy ]
 end

 resources :answers do
  resources :comments, only: [:new, :create, :update]
  resources :votes, only: [:create, :destroy]
  patch 'best', on: :member
 end

 resources :comments, only: [ :edit, :destroy ]

  resources :users, only: [ :new, :show, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]

  root 'questions#index'

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

end

kiwi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,900' rel='stylesheet' type='text/css'>
  <title>Kiwi Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav>
      <img id="kiwi" src="http://pngimg.com/upload/kiwi_PNG4037.png"  />
      <h1 id="logo">Kiwi Overflow</h1>
      <ul>
        <% if logged_in? %>
          <li>welcome, <%= current_user.name %></li> |
          <li><%= link_to "Post a Question", new_question_path %></li> |
          <li><%= link_to("Log Out", session_path(current_user), method: :delete) %></li> ||
        <% else %>
          <li><%= link_to "Register", register_path %></li> |
          <li><%= link_to "Login", login_path %></li> ||
        <% end %>
          <li><%= link_to "All Questions", questions_path %></li>
      </ul>
    </nav>
  </header>
  <main>
      <%= yield %>
  </main>
  <footer>
    <p>2016 &copy; Jeff, Luis, Zach, and Nicola</p>
  </footer>

</body>
</html>