kiwi/config/routes.rb
Rails.application.routes.draw do

 resources :questions do
  resources :comments, only: [:new, :create, :update]
  resources :answers, only: [:create]
  resources :votes, only: [ :create, :destroy ]
 end

 resources :answers do
  resources :comments, only: [:new, :create, :update]
  resources :votes, only: [:create, :destroy]
  patch 'best', on: :member
 end

 resources :comments, only: [ :edit, :destroy ]

  resources :users, only: [ :new, :show, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]

  root 'questions#index'

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'

end

kiwi/app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable

  belongs_to :user
  belongs_to :question

  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates_presence_of :content, :user, :question

  #make answer finding a concern of answer
  def self.best_for_question question
    find_by(id: question.best_answer_id)
  end
end

kiwi/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  add_flash_types(:alert)

  def create
    @answer = Answer.new(answer_params)
    if request.xhr?
       if @answer.save
        render partial: "answers/answer_show", layout: false, locals: { answer: @answer}
      end
    else
      if @answer.save
        redirect_to question_path(id: @answer.question_id)
      else
        # Errors are lost on redirect (it's a new request)
        @errors = @answer.errors.full_messages
        redirect_to question_path(id: @answer.question_id)
      end
    end
  end

  def best
    # binding.pry
    @answer = Answer.find_by(id: params[:id])
    @answer.question.update(best_answer_id: @answer.id)
    redirect_to question_path(id: @answer.question_id)
  end

  private

  def answer_params
    params.require(:answer).permit(:content,:user_id,:question_id)
  end

end

kiwi/app/views/answers/_answer_show.html.erb
<div class="answer">
  <div class="vote-container">
    <ul class="vote-attributes">
      <li id="up-vote"><%= link_to '&#x25B2'.html_safe, answer_votes_path(answer, vote: {direction: '1'}), method: :post %></li>
      <li><%= answer.sum_of_votes %></li>
      <li id="down-vote"><%= link_to '&#x25BC'.html_safe, answer_votes_path(answer, vote: {direction: '-1'}), method: :post %></li>
      <%# binding.pry %>
      <% if answer.question.best_answer_id == answer.id %>
        <li>BEST!</li>
      <% else %>
        <% if answer.question.user == current_user && !answer.question.best_answer_id %>
          <li>
            <%= link_to "Best?", best_answer_path(answer.id), method: :patch %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <span class="user-time">Answered by <%= answer.user.name %> <%= std_format_date(answer.created_at) %></span>
  <p><%= answer.content %></p>

  <% if !answer.comments.empty? %>
    <h5>Comments:</h5>
    <div class="comments">
      <% answer.comments.order(:created_at).each do |comment| %>
        <p class="comment"><%= comment.content %> &bull;
          <span class="user-time"><%= comment.user.name %> <%= std_format_date(comment.created_at) %></span><% if current_user == comment.user %> &bull; <%= link_to "Edit", edit_comment_path(comment.id) %> &bull; <%= link_to "Delete",comment_path(comment.id), method: :delete, data: {confirm: 'Are you sure?'}  %><% end %>
        </p>
      <% end %>
    </div>
  <% end %>

  <% if logged_in? %>
    <%= link_to "Add Comment", new_answer_comment_path(answer.id) %>
  <% end %>
</div>

kiwi/app/views/answers/_form.html.erb
<%= form_for [@question, @question.answers.build] do |f| %>
  <fieldset id="form" class="container">
    <div id="input-options">
      <%= f.text_area :content %>
      <%= f.hidden_field :question_id %>
      <% if logged_in? %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
    </div>
    <%= f.submit 'Post Answer' %>
  </fieldset>
<% end %>

kiwi/app/views/answers/new.html.erb
new.html.erb